<!DOCTYPE html>
<html>
<head>
    <title>Scruffy</title>
    <style>
    .button {
        display: inline-block;
        background: #A44;
        padding: 10px;
        text-align: center;
        border-radius: 5px;
        color: white;
        font-weight: bold;
        text-decoration: none;
    }
    </style>
</head>
<body>
    <h1>Scruffy-Server</h1>
    <p>Write simple formatted text and get an instant <strong>UML</strong> diagrams out of it.</p>
    <h2>Use Cases:</h2>
    <p>While most UML tools are for long term heavy diagrams, Scruffy is there for a <em>short diagrams</em>.</p>
    <ul>
        <li><em>Temporary</em> diagram to share with your colleagues</li>
        <li>Quickly get an image for your <em>wiki</em></li>
        <li>Textual form you could sneak directly inside your <em>code documentation</em></li>
        <li><em>Generate</em> the text, and it makes the diagram for you.</li>
    </ul>
    <h2>Online!</h2>
    <p>
        Start a new <a class="button" href="/class/"><strong>UML Class Diagram</strong></a> or <a class="button" href="/sequence/"><strong>UML Sequence Diagram</strong></a>.
    </p>
    <h2>FAQ</h2>
    <h3>Can I make my diagram private?</h3>
    <p>
        In a sense they are. They can be shared but unlike most links, sharing the link is sharing the entire source.
        So all possible diagrams can be generated by randomly guessing URLs. Making them private would have no real
        security benefit. If it's so secretative, you can always run Scruffy on your own machine.
    </p>
    <h3>Feedbacks/complains/suggestions...</h3>
    <p>
        <ol>
            <li>Check <a href="https://github.com/wernight/scruffy-server">Scruffy-Server GitHub</a> project and create an issue.</li>
            <li>Once you're ready, work on it and submit your changes.</li>
        </ol>
    </p>
    <a href="https://github.com/wernight/scruffy-server"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://github-camo.global.ssl.fastly.net/365986a132ccd6a44c23a9169022c0b5c890c387/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f7265645f6161303030302e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_right_red_aa0000.png"></a>
</body>
</html>
